services:
  cms-pixiv:
    build:
      context: ./kanmi-cms-pixiv
    env_file:
      - ./common/config/user-config.env
      - ./common/config/setup-authware.env
    networks:
      kanmi_system:
        aliases:
          - twitter.cms.kanmi.acr
    volumes:
      - persistent_data:/across/sequenzia-framework/data
      - ./common/config/user-config.json:/across/user-config.json:ro
    restart: on-failure
