services:
  database:
    image: mysql:8-oracle
    env_file: ./common/config/user-config.env
    networks:
      kanmi_system:
        aliases:
          - sql.backend.acr
    volumes:
      - ./base/base_v20.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    restart: unless-stopped
  mq:
    image: rabbitmq:3-management-alpine
    env_file: ./common/config/user-config.env
    volumes:
      - mq_data:/var/lib/rabbitmq/
    networks:
      kanmi_system:
        aliases:
          - mq.backend.acr
    restart: unless-stopped

  watchdog:
    build:
      context: ./kanmi-watchdog
    env_file:
      - ./common/config/user-config.env
    networks:
      kanmi_system:
        aliases:
          - watchdog.kanmi.acr
    depends_on:
      - database
    volumes:
      - ./common/data/:/data/
      - ./kanmi-watchdog/config.json:/across/watchdog/config.json:ro
      - ./kanmi-watchdog/watchdog.config.json:/across/watchdog/watchdog.config.json:ro
    restart: unless-stopped
  authware:
    build:
      context: ./kanmi-discord-authware
    env_file:
      - ./common/config/user-config.env
      - ./common/config/setup-authware.env
    networks:
      kanmi_system:
        aliases:
          - authware.kanmi.acr
    depends_on:
      - database
      - mq
    volumes:
      - ./common/config/setup-authware.env:/across/setup-authware.env
      - ./common/config/user-config.json:/across/user-config.json:ro
    restart: unless-stopped
  framework:
    build:
      context: ./kanmi-discord-framework
    env_file: ./common/config/user-config.env
    networks:
      kanmi_system:
        aliases:
          - framework.kanmi.acr
    depends_on:
      - database
      - mq
      - authware
    volumes:
      - ./common/config/user-config.json:/across/user-config.json:ro
    restart: unless-stopped
  fileworker:
    build:
      context: ./kanmi-discord-fileworker
    env_file: ./common/config/user-config.env
    networks:
      kanmi_system:
        aliases:
          - fileworker.kanmi.acr
    depends_on:
      - database
      - mq
      - authware
    volumes:
      - ./common/config/user-config.json:/across/user-config.json:ro
      - ./common/data/:/data/
    restart: unless-stopped
  web:
    build:
      context: ./sequenzia-web
    env_file: ./common/config/user-config.env
    ports:
      - 3000:3000
    networks:
      kanmi_system:
        aliases:
          - sequenzia.acr
    volumes:
      - ./common/config/user-config.json:/across/user-config.json:ro
      - ./common/data/:/data/
    restart: unless-stopped

networks:
  kanmi_system:
    ipam:
      driver: default
      config:
        - subnet: 192.168.85.0/24
    driver_opts:
      com.docker.networks.bridge.name: br-kanmi_system

volumes:
  db_data:
  mq_data:
