services:
  database:
    image: mysql:8-oracle
    environment:
      MYSQL_ROOT_PASSWORD: Km9@v-A6F%FdSt!6ja8+
    networks:
      kanmi_system:
        aliases:
          - sql.backend.acr
    volumes:
      - ./base/base_v20.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
    restart: unless-stopped
  mq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: kanmi
      RABBITMQ_DEFAULT_PASS: t2QpQTmgP32nWThE3eZ4
    volumes:
      - mq_data:/var/lib/rabbitmq/
    networks:
      kanmi_system:
        aliases:
          - mq.backend.acr
    restart: unless-stopped

  authware:
    build:
      context: ./kanmi-discord-authware
    environment:
      WAIT_HOSTS: sql.backend.acr:3306, mq.backend.acr:5672
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    networks:
      kanmi_system:
        aliases:
          - authware.kanmi.acr
    depends_on:
      - database
      - mq
    volumes:
      - ./common/config/user-config.json:/across/sequenzia-framework/user-config.json:ro
    restart: on-failure

  framework:
    build:
      context: ./kanmi-discord-framework
    environment:
      WAIT_HOSTS: sql.backend.acr:3306, mq.backend.acr:5672
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    networks:
      kanmi_system:
        aliases:
          - framework.kanmi.acr
    depends_on:
      - database
      - mq
      - authware
    volumes:
      - ./common/config/user-config.json:/across/sequenzia-framework/user-config.json:ro
    restart: on-failure

  fileworker:
    build:
      context: ./kanmi-discord-fileworker
    environment:
      WAIT_HOSTS: sql.backend.acr:3306, mq.backend.acr:5672
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    networks:
      kanmi_system:
        aliases:
          - fileworker.kanmi.acr
    depends_on:
      - database
      - mq
      - authware
    volumes:
      - ./common/config/user-config.json:/across/sequenzia-framework/user-config.json:ro
      - ./common/data/:/data/
  restart: on-failure

  web:
    build:
      context: ./sequenzia-web
    environment:
      WAIT_HOSTS: sql.backend.acr:3306, mq.backend.acr:5672
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    ports:
      - 3000:3000
    networks:
      kanmi_system:
        aliases:
          - sequenzia.acr
    volumes:
      - ./common/config/user-config.json:/across/sequenzia-web/user-config.json:ro
      - ./common/data/:/data/
    restart: on-failure

networks:
  kanmi_system:
    ipam:
      driver: default
      config:
        - subnet: 192.168.85.0/24
    driver_opts:
      com.docker.networks.bridge.name: br-kanmi_system
volumes:
  db_data:
  mq_data:
