services:
  frontend:
    build:
      context: ./sequenzia-proxy
    env_file: ./common/config/user-config.env
    ports:
      - 80:80
      - 443:443
    networks:
      kanmi_system:
        aliases:
          - frontend.acr
    volumes:
      - ./common/well-known/:/well-known/:ro
      - ./common/ssl/:/certs/
    restart: on-failure
    logging:
      options:
        max-size: "10m"
        max-file: "3"
