services:
  kanmi-database:
    image: mysql:8-oracle
    container_name: kanmi-database
    environment:
      MYSQL_ROOT_PASSWORD: Km9@v-A6F%FdSt!6ja8+
    networks:
      kanmi_system:
        aliases:
          - sql.backend.acr
    volumes:
      - ./base/base_v20.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql
  kanmi-mq:
    image: rabbitmq:3-management-alpine
    container_name: kanmi-mq
    environment:
      RABBITMQ_DEFAULT_USER: kanmi
      RABBITMQ_DEFAULT_PASS: t2QpQTmgP32nWThE3eZ4
    volumes:
      - mq_data:/var/lib/rabbitmq/
    networks:
      kanmi_system:
        aliases:
          - mq.backend.acr

  kanni-authware:
    build:
      context: ./kanmi-discord-authware
    environment:
      SETUP_TYPE: storage
      SETUP_SERVERID: 991736826568134797
      WAIT_HOSTS: sql.backend.acr:3306, mq.backend.acr:5672
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    networks:
      kanmi_system:
        aliases:
          - authware.kanmi.acr
    depends_on:
      - kanmi-database
      - kanmi-mq
    volumes:
      - ./common/config/user-config.json:/across/sequenzia-framework/user-config.json:ro

networks:
  kanmi_system:
    ipam:
      driver: default
      config:
        - subnet: 192.168.85.0/24
    driver_opts:
      com.docker.networks.bridge.name: br-kanmi_system
volumes:
  db_data:
  mq_data:
