#!/bin/sh

echo "Sequenzia Server Control (Alpha)"

# Using specific lines as config to prevent compatibility issues with using specific commands that are not supported by Win, Linux,and Unix.
DCL=''
DFL='-f docker-compose.yaml'
getServices() {
  for i in $(sed -n '1p' ./common/config/controller.dat 2> /dev/null || echo 'default proxy'); do
    case "$i" in
      default) ;;
      core)
        DCL="database mq framework authware";;
      uploader)
        DCL="mq framework fileworker";;
      external)
        echo "WARNING! Backend SQL and MQ ports are exposed!";
        DFL="${DFL} -f docker-compose-external.yaml";;
      manager)
        DFL="${DFL} -f docker-compose-manager.yaml";;
      router)
        DFL="${DFL} -f docker-compose-router.yaml";;
      proxy)
        DFL="${DFL} -f docker-compose-frontend.yaml";;
      samba)
        DFL="${DFL} -f docker-compose-share.yaml";;
      cms-twitter)
        DFL="${DFL} -f docker-compose-cms-twitter.yaml";;
      cms-pixiv)
        DFL="${DFL} -f docker-compose-cms-pixiv.yaml";;
      cms-rss)
        DFL="${DFL} -f docker-compose-cms-rss.yaml";;
      cms-spider)
        DFL="${DFL} -f docker-compose-cms-spider.yaml";;
      *)
        DCL="${DCL} ${i}";;
    esac
  done
}
ALL_DFL='-f docker-compose.yaml -f docker-compose-frontend.yaml -f docker-compose-router.yaml -f docker-compose-external.yaml -f docker-compose-manager.yaml -f docker-compose-share.yaml -f docker-compose-cms-twitter.yaml -f docker-compose-cms-pixiv.yaml -f docker-compose-cms-rss.yaml -f docker-compose-cms-spider.yaml'
full_stop() {
  docker compose ${ALL_DFL} down;
}
comp_name() {
  docker compose ${DFL} ps $1 | tail -n +2 | awk '{ print $1 }'
}
is_running() {
  case "$(comp_name $1)" in
    no*) echo "n";;
    *) echo "y";;
  esac
}

if [ -n "$1" ]
then
  getServices;
	# shellcheck disable=SC2086
	case "$1" in
		mode)
		  if [ -n "$2" ]
      then
        case "$2" in
          append)
            if [ -n "$3" ]
            then
              echo "$(cat ./common/config/controller.dat 2> /dev/null || echo 'default proxy') $3" > ./common/config/controller.dat
            else
              echo "You need to specify a mode to append"
            fi;;
          *) echo "$2" > ./common/config/controller.dat;;
        esac
      fi
      echo "Operator Mode to: $(cat ./common/config/controller.dat 2> /dev/null || echo 'default proxy')"
		  ;;
		test-core) docker compose up database mq framework authware;;
		test)
		  if [ -n "$2" ]
		  then
        docker compose ${DFL} up $2
      else
        docker compose ${DFL} up ${DCL}
      fi;;
		start)
		  if [ -n "$2" ]
		  then
        docker compose ${DFL} up $2 -d
      else
        docker compose ${DFL} up ${DCL} -d
      fi;;
		stop)
		  if [ -n "$2" ]
      then
        docker compose ${DFL} stop $2 &&
        docker compose ${DFL} rm -f $2
      else
        full_stop
      fi;;
		restart)
		  if [ -n "$2" ]
      then
        docker compose ${DFL} restart $2
      else
        docker compose ${DFL} restart ${DCL}
      fi;;
		reset)
			if [ -n "$2" ]
			then
				docker compose ${DFL} stop $2
				docker compose ${DFL} rm $2
				docker compose ${DFL} up $2 -d
			else
			  full_stop &&
			  docker compose ${DFL} up ${DCL} -d;
			fi;;
		config) nano common/config/user-config.json ;;
		env) nano common/config/user-config.env ;;
		setupaw) nano common/config/setup-authware.env ;;
		status) docker compose ${ALL_DFL} ps;;
		logs) docker compose ${ALL_DFL} logs $2 -f;;
    certs)
      if [ -n "$2" ]
      then
        case "$2" in
              request)
                if [ "$(is_running frontend)" = "y" ]; then
                  docker exec -it "$(comp_name frontend)" sh -c 'mkdir -p /certs/certbot && certbot certonly --config-dir /certs/certbot --webroot-path="/www-root/" --webroot -d $EXTERNAL_FQDN --email $CERT_EMAIL --non-interactive --expand --agree-tos'
                  docker compose -f docker-compose.yaml -f docker-compose-frontend.yaml down frontend &&
                  docker compose -f docker-compose.yaml -f docker-compose-frontend.yaml up frontend -d &&
                  echo "The server should be available soon, Please visit your domain name to confirm your certificates are correctly loaded!"
                else
                  echo "Frontend Proxy is not running or is not configured!"
                fi;;
              selfsigned)
                if [ "$(is_running frontend)" = "y" ]; then
                  docker exec -it "$(comp_name frontend)" openssl req -new -x509 -nodes -days 365 -sha256 -subj "/C=JP/ST=Tokyo/L=Academy City/O=Academy City Research - Non-Affiliated Subsidiary/CN=localhost" -addext "subjectAltName=DNS:localhost" -newkey rsa:2048 -keyout /certs/frontend.key -out /certs/frontend.crt &&
                  docker compose -f docker-compose.yaml -f docker-compose-frontend.yaml stop frontend &&
                  docker compose -f docker-compose.yaml -f docker-compose-frontend.yaml up frontend -d &&
                  echo "IMPORTANT! MAC OS handles self signed certificates poorly and you will have to get a real certificate from certbot once your ready to complete"
                else
                  echo "Frontend Proxy is not running or is not configured!"
                fi;;
              reset) rm -rf ./common/keys/certbot ;;
              *) echo "Invalid command";;
            esac
      else
        echo "Missing command"
      fi
      ;;
		build)
			if [ -n "$2" ]
			then
				docker compose ${ALL_DFL} stop $2 &&
				docker compose ${DFL} build --no-cache $2 &&
				docker compose ${ALL_DFL} up $2 -d &&
				docker system prune -f &&
				echo "################################################################" &&
				echo "Build of $2 Completed Successfully and Restarted" &&
				echo "################################################################"
			else
				git pull &&
				full_stop &&
				docker system prune -f &&
				docker compose ${DFL} build --no-cache &&
				echo "################################################################" &&
				echo "Build Completed Successfully" &&
				echo "################################################################" &&
				echo "" &&
				docker compose ${DFL} up ${DCL} -d
			fi
			;;
		router)
		  if [ -n "$2" ]
      then
        case "$2" in
          start)
            if [ "$(is_running watchdog)" = "y" ]; then
              docker exec -it "$(comp_name lantis-router)" sh -c "cd /lantis; bash ./lantis.bash -L"
            else
              echo "LANTIS Router is not running"
            fi;;
          stop)
            if [ "$(is_running watchdog)" = "y" ]; then
              docker exec -it "$(comp_name lantis-router)" sh -c "cd /lantis; bash ./lantis.bash -K"
            else
              echo "LANTIS Router is not running"
            fi;;
          keygen-setup)
            ssh-keygen -f ./common/keys/setup.key -N '' -b 2048 &&
            echo "Your Setup Public Key is:" &&
            cat ./common/keys/setup.key.pub &&
            echo '';;
          keygen-master)
            ssh-keygen -f ./common/keys/lantis.key -N '' -b 2048 &&
            echo "Your LANTIS Public Key is:" &&
            cat ./common/keys/setup.key.pub &&
            echo '';;
          pubkeys)
            echo "Your Setup Public Key is:" &&
            cat ./common/keys/setup.key.pub &&
            echo ' ' &&
            echo "Your LANTIS Public Key is:" &&
            cat ./common/keys/setup.key.pub &&
            echo '';;
          config) nano ./common/config/connections/*.rc;;
          *) echo "Invalid command";;
        esac
      else
        echo "Missing command"
      fi
      ;;
		refresh)
		  echo "Updating to latest commit..."
		  UPDATE_COMMAND='git fetch && git reset --hard origin && npm install'
		  if [ "$(is_running watchdog)" = "y" ]; then
        docker exec -it "$(comp_name watchdog)" sh -c "cd /across/watchdog/ && " &&
        docker compose restart watchdog &&
        sleep 5 &&
        docker exec -it "$(comp_name watchdog)" sh -c '/wait && mysql -h "$DATABASE_HOST" -u "$DATABASE_USERNAME" -p"$DATABASE_PASSWORD" kanmi_system < /across/compliance_v20.sql';
      fi
      if [ "$(is_running authware)" = "y" ]; then
        docker exec -it "$(comp_name authware)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}"  &&
        docker compose restart authware
      fi
      if [ "$(is_running framework)" = "y" ]; then
        docker exec -it "$(comp_name framework)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}"  &&
        docker compose restart framework
      fi
      if [ "$(is_running fileworker)" = "y" ]; then
        docker exec -it "$(comp_name fileworker)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}"  &&
        docker compose restart fileworker
      fi
      if [ "$(is_running web)" = "y" ]; then
        docker exec -it "$(comp_name web)" sh -c "cd /across/sequenzia-web/ && ${UPDATE_COMMAND}"  &&
        docker compose restart web
      fi
      if [ "$(is_running lantis-router)" = "y" ]; then
        docker exec -it "$(comp_name lantis-router)" sh -c "cd /lantis && git fetch && git reset"  &&
        docker compose restart lantis-router
      fi
      echo "################################################################" &&
      echo "Refresh Completed - This is NOT persistent and you will need to" &&
      echo "build to persistently update the images" &&
      echo "################################################################" &&
      echo "";;
		prerelease)
		  echo "Updating to latest prerelease commit..."
		  if [ "$(git rev-parse --abbrev-ref HEAD)" = "prerelease" ]; then
		    UPDATE_COMMAND='git fetch; [ "$(git show-ref prerelease | wc -l)" -eq 0 ] && echo "No Update Available" && exit 1 || git reset --hard "origin/prerelease" && npm install'
		    if [ -n "$2" ]
        then
          if [ "$(is_running $2)" = "y" ]; then
            if [ "$2" == "web" ]; then
              docker exec -it "$(comp_name $2)" sh -c "cd /across/sequenzia-web/ && ${UPDATE_COMMAND}"
            elif [ "$2" == "watchdog" ]; then
              docker exec -it "$(comp_name $2)" sh -c "cd /across/watchdog/ && ${UPDATE_COMMAND}"
            else
              docker exec -it "$(comp_name $2)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}"
            fi
            docker compose restart $2;
          fi
        else
          if [ "$(is_running watchdog)" = "y" ]; then
            docker exec -it "$(comp_name watchdog)" sh -c "cd /across/watchdog/ && ${UPDATE_COMMAND}" &&
            docker compose restart watchdog &&
            sleep 5;
            docker exec -it "$(comp_name watchdog)" sh -c '/wait && mysql -h "$DATABASE_HOST" -u "$DATABASE_USERNAME" -p"$DATABASE_PASSWORD" kanmi_system < /across/compliance_v20.sql'
          fi
          if [ "$(is_running authware)" = "y" ]; then
            docker exec -it "$(comp_name authware)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}" &&
            docker compose restart authware;
          fi
          if [ "$(is_running framework)" = "y" ]; then
            docker exec -it "$(comp_name framework)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}" &&
            docker compose restart framework;
          fi
          if [ "$(is_running fileworker)" = "y" ]; then
            docker exec -it "$(comp_name fileworker)" sh -c "cd /across/sequenzia-framework/ && ${UPDATE_COMMAND}" &&
            docker compose restart fileworker;
          fi
          if [ "$(is_running web)" = "y" ]; then
            docker exec -it "$(comp_name web)" sh -c "cd /across/sequenzia-web/ && ${UPDATE_COMMAND}" &&
            docker compose restart web;
          fi
        fi
        echo "################################################################" &&
        echo "Prerelease Refresh Completed - So things may be broken..." &&
        echo "This is NOT persistent and you will need to update environment" &&
        echo "file to use prerelease and build to persistently update the images" &&
        echo "################################################################" &&
        echo ""
      else
        echo "Please run 'git checkout prerelease' to update the compose scripts. This is to ensure that the latest compliance file is used (if needed)."
      fi;;
		fbuild)
			git pull &&
			docker build --no-cache -t kihara/across-base:latest ./base &&
			docker tag kihara/across-base:latest kihara/across-base:v20 &&
			full_stop &&
			docker compose build --no-cache &&
			docker system prune -f &&
			echo "################################################################" &&
			echo "Build Completed Successfully" &&
			echo "################################################################" &&
			echo "" &&
			echo "Please use your appropriate start command or just use 'start'"
			;;
		publish) docker push kihara/across-base:latest && docker push kihara/across-base:v20;;
		backup)
		  docker compose up database -d &&
		  docker exec -it "$(docker compose ps database | tail -n +2 | awk '{ print $1 }')" sh /backup.sh
		  echo "DANGER!!! BACKUP FILES CONTAIN UNENCRYPTED USER DATA AND ARE CONSIDERED PROTECTED CONFIDENTIAL DATA"
      echo "YOU ARE RESPONSIBLE FOR THE SECURITY OF THESE FILES, ACADEMY CITY RESEARCH AND DIGITAL ARTIFACTS LLC"
      echo "IS NOT RESPONSIBLE FOR ANY DAMAGES CAUSED BY IMPROPER HANDLING OF BACKUP FILES";;
		restore)
		  cp "$(ls -Art ./common/data/backup/database-* | tail -n 1)" ./common/data/backup/restore.sqldump.bz2;
		  full_stop &&
		  docker compose up database -d &&
		  docker exec -it "$(docker compose ps database | tail -n +2 | awk '{ print $1 }')" sh /restore.sh &&
		  echo "You can now start Sequenzia normally!";;
		export)
		  full_stop &&
      docker compose up database -d &&
      docker exec -it "$(docker compose ps database | tail -n +2 | awk '{ print $1 }')" sh /backup.sh kickstart.sql &&
      tar --exclude=./common/config/compliance* \
      --exclude=./common/config/example.*  \
      --exclude=./common/data/upload \
      --exclude=./common/data/.temp \
      --exclude=./common/data/.web-upload \
      --exclude=./common/data/backup/database-* \
      -cvjf "./sequenzia-kickstart-$(date +%Y-%m-%d_%H-%M).tar.bz2" \
      ./common/data/ \
      ./common/config/ \
      ./common/www-root/ \
      ./common/persistent/ \
      ./common/ssl/ \
      ./common/keys/ \
      ./sequenzia-web/public &&
      rm ./common/data/backup/kickstart.sql &&
      full_stop &&
      echo "Export Completed, Please take the kickstart file to your new server or store this for later!"
      echo ""
      echo "DANGER!!! KICKSTART FILES CONTAIN UNENCRYPTED USER DATA AND ARE CONSIDERED PROTECTED CONFIDENTIAL DATA"
      echo "YOU ARE RESPONSIBLE FOR THE SECURITY OF THESE FILES, ACADEMY CITY RESEARCH AND DIGITAL ARTIFACTS LLC"
      echo "IS NOT RESPONSIBLE FOR ANY DAMAGES CAUSED BY IMPROPER HANDLING OF KICKSTART FILES";;
		import)
      if [ "$(ls -Art ./sequenzia-kickstart* | wc -l)" -gt 0 ]; then
  		  tar xvf "$(ls -Art ./sequenzia-kickstart* | tail -n 1)" &&
	  	  full_stop &&
		    docker compose build --no-cache &&
		    docker compose up database -d &&
  		  docker exec -it "$(docker compose ps database | tail -n +2 | awk '{ print $1 }')" sh /restore.sh kickstart.sql
	  	  rm ./common/data/backup/kickstart.sql &&
		    echo "Import Completed, Ready to start Sequenzia!"
		  else
        echo "No kickstart file found!"
      fi;;
		upload)
		  docker compose up database -d &&
		  docker exec -it "$(docker compose ps database | tail -n +2 | awk '{ print $1 }')" sh /backup.sh && cp common/data/backup/database-* common/data/upload/Backup
		  echo "The backup file should now be uploading to Sequenzia's Backup folder."
		  echo ""
		  echo "If you removed that folder then your in big fucking trouble, because it will upload to the data channel..."
		  echo "DANGER!!! BACKUP FILES CONTAIN UNENCRYPTED USER DATA AND ARE CONSIDERED PROTECTED CONFIDENTIAL DATA"
      echo "YOU ARE RESPONSIBLE FOR THE SECURITY OF THESE FILES, ACADEMY CITY RESEARCH AND DIGITAL ARTIFACTS LLC"
      echo "IS NOT RESPONSIBLE FOR ANY DAMAGES CAUSED BY IMPROPER HANDLING OF BACKUP FILES";;
		*) echo "$1 is not an valid command" ;;
	esac
else
	echo ""
	echo "start      - Boot server"
	echo "stop       - Shutdown server"
	echo "restart    - Restart server"
	echo "reset      - Reset server OS"
	echo '             [?] Above commands support specifying a component or "list"'
	echo 'mode       - Show or Set Operator Mode'
	echo '- append         - Append mode to operator mode'
	echo ''
	echo 'router     - Interface with embedded LANTIS router (must be enabled)'
	echo '- start          - Start all routes'
	echo '- stop           - Kill all routes'
	echo '- keygen-setup   - Generate a new keypair for setup'
	echo '- keygen-master  - Generate a new keypair for transport'
	echo '- pubkeys        - Display public keys'
	echo '- config         - Edit the Connections'
	echo ''
	echo "status     - Status of components"
	echo "logs       - Show components logs"
	echo ""
	echo "test       - Boot server in foreground"
	echo "test-core  - Boot Core Components in foreground"
	echo ""
	echo "config     - Edit User Configuration File"
	echo "env        - Edit User Environment File"
	echo "setupaw    - Edit AuthWare Configuration File"
	echo ""
	echo 'certs      - Manage SSL Certificates'
	echo '- request        - Request new certificate from Certbot'
  echo '- selfsigned     - Generate self signed certificate'
  echo '- reset          - Remove Certbot Certificates and Settings'
  echo ''
	echo '[!] You MUST have configured a valid "EXTERNAL_FQDN", "CERT_EMAIL", and'
	echo '    have configured LANTIS or Port Forwarding for remote access'
	echo ""
	echo "refresh    - Update to latest commit (Non-Persistent)"
	echo "prerelease - Update to latest prerelease commit (Non-Persistent)"
	echo "build      - Rebuild Element(s) and Reload Static Files"
	echo "fbuild     - Rebuild ACROSS, Update base files, and Build Elements"
	echo "publish    - Publish ACROSS Images (Contributors Only)"
	echo ""
	echo "upload     - Backup Database to Discord #backup Channel"
	echo "backup     - Backup Database to /common/data/backup"
	echo "restore    - Restore last Database from /common/data/backup"
	echo ""
	echo "export     - Export Kickstart Tarball"
	echo "import     - Import Kickstart Tarball"
fi
